### ISSUE TITLE
ddns-path parameter interpretation issues and pidfile permission denied

### ISSUE THREAD

**Issue by sigmoidal** [troglobit/inadyn#152] opened 2016-12-19 13:16 UTC
Hi,

When the ddns-path contains the + symbol, then it is interpreted as a white space:

`DkaLsrOw+mkqC1FerH+m/A==`

becomes

`DkaLsrOw mkqC1FerH m/A==`

If I exchange it with %2B, then it complains due to modifier interpretation:

> Dec 19 15:00:01 sss inadyn[2508]: Failed creating pidfile: Permission denied
> Dec 19 15:00:02 sss inadyn[2508]: Update forced for alias myhost.example.org, new IP# xxx.xxx.xxx.xxx
> Dec 19 15:00:03 sss inadyn[2508]: Unknown format specifier in ddns-path: '2'
> Dec 19 15:00:03 sss inadyn[2508]: Invalid server URL: /updateip?hostname=myhost.example.orgr&key=DkaLsrOw%2BmkqC1FerH%2Bm/A==`

There is also another issue visible here with writing the pidfile, which it cannot be performed because the user running inadyn is unprivileged. Actually it should not write a pidfile at all since I run it like this:

/usr/sbin/inadyn -1 -n -f /etc/inadyn/inadyn.conf

the -1 should need no pidfile in general, or?

thanks

**Comment by troglobit** [comment] 2016-12-19 18:06
I see, we should do URL encoding (of course) of the path components.  As it is now Inadyn stumbles
if %2B (or similar) is entered, since it tries to to format specifier expansion.

As a temporary workaround, try `%%2B` ... 

Good point about the pid file and `-1`, fixed on master.

**Comment by sigmoidal** [comment] 2016-12-20 11:46
Thanks for the pidfile fix. It seems to work. The workaround though doesn't:

inadyn[21918]: Unknown format specifier in ddns-path: '%'

true need to urlencode to tackle this properly. The logic with the modifiers probably has be modified also?

**Comment by troglobit** [comment] 2016-12-21 16:37
I just realized when I read your reply ... sorry about that.  Should be fixed in 6fc5a9d.

Yep, a simple `urlencode()` of the rest of the custom server URL should do the trick. Do you think you could whip something up in a pull request? :smirk:

**Closed** 2017-01-05 15:52 UTC

**Comment by troglobit** [comment] 2017-01-05 15:56
I've added some untested code in 02e22f2 for this now, hopefully it works for cases like yours. 

The logic with the format specifiers should still work as intended, the reserved specifiers are not part of the HEX codes the URL encoding translates to.  The order is to first translate format specifiers and then do the URL encoding right before the server transaction.
