### ISSUE TITLE
twoDNS is not working anymore

### ISSUE THREAD

**Issue by Makishima** [troglobit/inadyn#342] opened 2021-02-10 18:10 UTC
Hello!
My old inadyn.conf is not working anymore with twoDNS, I can't figure out what's wrong.
I've removed some sensitive data but the password and login is 100% actual 
```
custom twoDNS {
username       = XXXX
password       = XXXX
checkip-server = checkip.two-dns.de
checkip-path   = /
ddns-server    = update.twodns.de
ddns-path      = "/update?hostname="
hostname       = XXXX
}
```

**Comment by troglobit** [comment] 2021-02-10 18:12
Duplicate of #314

**Comment by troglobit** [comment] 2021-02-10 18:13
The only way we could support their v1 API was using the custom plugin.  To do it properly we need a dedicated plugin.  I suggest changing DDNS provider, e.g. freedns is really good.

**Comment by troglobit** [comment] 2021-02-10 18:13
Propose close, won't fix

**Comment by troglobit** [comment] 2021-02-10 18:48
@Makishima any comment before we close this?

**Comment by Makishima** [comment] 2021-02-10 18:53
Thanks for a quick response.
My last words are a hope that you will be adding support for twodns's v2 API someday :)

**Comment by troglobit** [comment] 2021-02-10 19:15
@Makishima that's not how open source works.  It works like this; you have an it and scratch it, then share that with the rest of the community. What you're describing is the traditional proprietary software development model where you pay me to help you.

**Closed by troglobit** 2021-02-10 19:15 UTC

**Comment by rettenbs** [comment] 2022-09-02 23:19
@Makishima twoDNS still works for me. You can still use the update URL as described [here](http://www.twodns.de/en/faqs). 
I use `ddns-path = "/update?hostname=%h&ip=%i"` to specify hostname and IP. (If the IP is omitted, twoDNS will guess it.)

I do not use the checkip server from twoDNS. This might cause the issue in your case.

This is also the only way to use twoDNS from a fritz box or something similar. Hence, I doubt that the remove support for this approach.
