### ISSUE TITLE
Custom port for `ddns-server` is ignored when SSL is enabled

### ISSUE THREAD

**Issue by MestreLion** [troglobit/inadyn#385] opened 2022-05-11 01:58 UTC
Using inadyn 2.8.1 from Ubuntu 22.04 jammy repository

`/etc/inadyn.conf` sets a custom port `1234`, and `ssl` is enabled as default:
```sh
custom ddnsp {
        ddns-server = example.com:1234
        ddns-path   = "/nic/update?hostname=%h&myip=%i"
        username    = user
        password    = pass
        hostname    = host
}
```
```console
helena@minipc ~ $ sudo inadyn --foreground -l debug
inadyn[87031]: In-a-dyn version 2.8.1 -- Dynamic DNS update client.
...
inadyn[86397]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[86397]: Sending IP# update to DDNS server, connecting to example.com([2606:2800:220:1:248:1893:25c8:1946]:443)
inadyn[86397]: Certificate OK
...
```
It ignores the `1234` setting and connects to the default `443` HTTPS port. If `ssl = false` is set in the config file, then it properly connects to the custom port (with HTTPS disabled, as expected):
```console
inadyn[87044]: Sending IP# update to DDNS server, connecting to example.com([2606:2800:220:1:248:1893:25c8:1946]:1234)
inadyn[87044]: Waiting (5 sec) for three-way handshake to complete ...
inadyn[87044]: Failed connecting to that server: retrying ...
inadyn[87044]: Sending IP# update to DDNS server, reconnecting to example.com([93.184.216.34]:1234)
inadyn[87044]: Waiting (5 sec) for three-way handshake to complete ...
inadyn[87044]: Failed connecting to example.com: Operation now in progress
```

**Comment by troglobit** [comment] 2022-05-11 02:54
Confirmed.  Same problem also on master, and thus v2.9.1.

Thank you for the excellent report, and example config to help reproduce the problem!

**Comment by troglobit** [comment] 2022-05-11 03:34
Should be fixed as of 0b5ac98.

**Closed** 2022-05-11 03:33 UTC
Labels: blocker

**Comment by MestreLion** [comment] 2022-05-11 03:45
Wow, thanks for the quick fix!

Is there a way to set up a PPA or similar so when 2.9.2 arrives it could be backported to Ubuntu 22.04? I doubt Ubuntu (or Debian) will land it in their official repositories for their current LTS

**Comment by troglobit** [comment] 2022-05-11 07:52
I've had my own builds, not a PPA, but since the new Debian maintainer took over I've not continued to maintain it.  It's not been feasible for me to maintain an entire PPA, there is simply not enough hours in a day.

I suggest reporting this to Debian/Ubuntu so they can backport that specific patch to their 2.8.1 release.  I will do a 2.9.2 later, in a couple of months I guess when I circle back to it.
