### ISSUE TITLE
' -p, --drop-privs=USER[:GROUP]' command line option does not work in version 2.0 beta

### ISSUE THREAD

**Issue by rtorrentuser** [troglobit/inadyn#113] opened 2015-12-14 04:29 UTC
Mon Dec 14 07:09:16 2015: Failed dropping privileges: Operation not permitted

**Comment by troglobit** [comment] 2015-12-14 06:10
Well ... do you run as root?

**Comment by troglobit** [comment] 2015-12-14 06:16
Argh, missed "2.0 beta" in your report ... and I can reproduce it here as well. 

Working on it ... master is slightly broken now since we're in the middle of transitioning to all the bells and whistles of 2.0 :smiley:

**Comment by troglobit** [comment] 2015-12-14 07:00
I've now fixed parts of this. But there are more issues to be ironed out before
master will be working as well (?) as the last stable release.

If you want something more stable, use released tarball in the meantime.

**Closed by troglobit** 2015-12-14 07:00 UTC

**Comment by rtorrentuser** [comment] 2015-12-14 08:26
Thanks, --drop-privs works now, so I'll be testing 2.0 beta...

There is one more problem in --drop-privs mode:

Mon Dec 14 10:20:46 2015: Failed creating pidfile: Permission denied

**Comment by troglobit** [comment] 2015-12-14 08:39
I know, there are several issue, it also does not create the Inadyn cache directory
with the proper user:group permissions suitable for --drop-privs, so unstable atm.

Very brave of you to continue trying to use master.  I'd still recommend going for a
stable release instead though.

**Comment by rtorrentuser** [comment] 2015-12-14 22:25
Thanks, --drop-privs works now, so I'll be testing 2.0 beta...

There is one more problem in --drop-privs mode:

Mon Dec 14 10:20:46 2015: Failed creating pidfile: Permission denied




On Mon, 14 Dec 2015 10:00:59 +0300, Joachim Nilsson  
<notifications@github.com> wrote:

>
> I've now fixed parts of this. But there are more issues to be ironed out  
> before
> master will be working as well (?) as the last stable release.
>
> If you want something more stable, use released tarball in the meantime.
>
> —
> Reply to this email directly or view it on GitHub.



--
