### ISSUE TITLE
Bug: Inadyn 2.8.1 "freezes" and does not detect(?)/apply updated  IPs after some time

### ISSUE THREAD

**Issue by bentolor** [troglobit/inadyn#399] opened 2022-11-29 09:01 UTC
Hi @troglobit !

Thanks for this great tool. Unfortunately it has changed its modi operandi from "just works" to "needs manual attention every few days/weeks" since I upgraded to the new version / configuration format via Ubuntu 22.04.

Situation is plain simple. `/etc/inadyn.conf` reads like

```
# /etc/inadyn.conf

# How often the IP is checked. The value denotes seconds
period = 300

provider default@freedns.afraid.org:1 {
 …
}
provider default@freedns.afraid.org:2 {
 …
}
```

Situation: It fails to update my IP every once in a while. I assume that maybe the Freedns provide might be temporarily unavailable at the moment of the IP change detected; a manual `sudo systemctl restart inadyn` immediately mends the situation.

Here the log. See my manual restart immediately caused an successful update!

```
Nov 27 12:38:56 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.127
Nov 27 12:38:56 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.127
Nov 27 12:38:56 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.127
Nov 27 12:38:56 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.127
Nov 27 12:38:56 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.127
Nov 28 05:18:48 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.140
Nov 28 05:18:48 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.140
Nov 28 05:18:48 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.140
Nov 28 05:18:48 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.140
Nov 28 05:18:48 neptun inadyn[2178777]: Update needed for alias ###, new IP# ###.140

[restart]

Nov 29 09:49:30 neptun systemd[1]: Stopping LSB: DynDNS client...
Nov 29 09:49:30 neptun inadyn[3369480]:  * Stopping DynDNS client inadyn
Nov 29 09:50:00 neptun inadyn[3369480]:    ...done.
Nov 29 09:50:00 neptun systemd[1]: inadyn.service: Deactivated successfully.
Nov 29 09:50:00 neptun systemd[1]: Stopped LSB: DynDNS client.
Nov 29 09:50:00 neptun systemd[1]: inadyn.service: Consumed 54.305s CPU time.
Nov 29 09:50:00 neptun systemd[1]: Starting LSB: DynDNS client...
Nov 29 09:50:00 neptun inadyn[3370340]:  * Starting DynDNS client  inadyn
Nov 29 09:50:00 neptun inadyn[3370340]:    ...done.
Nov 29 09:50:00 neptun systemd[1]: Started LSB: DynDNS client.
Nov 29 09:50:00 neptun inadyn[3370346]: In-a-dyn version 2.8.1 -- Dynamic DNS update client.
Nov 29 09:50:01 neptun inadyn[3370346]: Update forced for alias ###, new IP# ###.207
Nov 29 09:50:01 neptun inadyn[3370346]: Update forced for alias ###, new IP# ###.207
Nov 29 09:50:01 neptun inadyn[3370346]: Update forced for alias ###, new IP# ###.207
Nov 29 09:50:01 neptun inadyn[3370346]: Update forced for alias ###, new IP# ###.207
Nov 29 09:50:01 neptun inadyn[3370346]: Update forced for alias ###, new IP# ###.207
```

**I could now add a cronjob to restart the daemon regularily. But IMHO this would miss the point of inadyn, right?**

Any hints how to diagnose / bring the old stability back?

Thanks!

**Comment by troglobit** [comment] 2022-11-29 09:53
I'm not sure what this problem could be caused by.  The v2.8.1 release is a bit old and you should report the problem to your distribution rather than upstream.  We're at v2.10.0 now and don't have the possibility to support older releases.

**Comment by bentolor** [comment] 2022-11-29 11:22
For reference: Downstream bug report https://bugs.launchpad.net/ubuntu/+source/inadyn/+bug/1998208

**Comment by troglobit** [comment] 2022-11-29 12:29
There's been a lot of updates, and like I said above, I'm not sure what this problem could be caused by.  I use FreeDNS myself and haven't seen any problems.

You can have a look at https://github.com/troglobit/inadyn/releases to see if you find anything that may be relevant.  Sorry, I can't be of more help, but I don't really have the time to help you triage.

**Comment by troglobit** [comment] 2022-12-11 08:49
Unless this issue is reproducible with the latest release, I suggest closing this.

**Comment by bentolor** [comment] 2022-12-11 11:30
Unable to find a distribution of current version for current Ubuntu/Debian.

**Closed** 2022-12-11 11:29 UTC

**Comment by troglobit** [comment] 2022-12-11 12:21
You have the option to build it yourself, of course, otherwise you'll have to file a bug report with the maintainer downstream (Debian).  [Their system tracks new releases](https://tracker.debian.org/pkg/inadyn), so eventually they will get to it, I guess.
