### ISSUE TITLE
IPv6 support for checkip and update API servers

### ISSUE THREAD

**Issue by acolomb** [troglobit/inadyn#186] opened 2017-12-11 21:39 UTC
First of all, thanks for this fantastic piece of software. Finally I found a modern, sensible DDNS update client that is customizable enough for most providers.

My use case requires only IPv6 address handling (ISP gives only DS-Lite) and I'd still like to use the external checkip server support instead of specifying a fixed interface. This way, whichever interface is deemed most appropriate for outgoing internet connections will also be the one whose IPv6 address is reported.

However, the `checkip-server` option currently does not support IPv6-only servers. If I specify e.g. `checkipv6.dynu.com`, Inadyn tells me:

```inadyn[21941]: Failed resolving hostname checkipv6.dynu.com: No address associated with hostname```

The service naturally only has an AAAA record, which apparently Inadyn does not try to resolve. I currently work around this by using `checkip-command  = "curl -s -6 https://checkipv6.dynu.com"`.

Inadyn's check of the DDNS domain's current IP address seems to fail alike. For a hostname with only an AAAA record to be updated, I get the above error message also for a lookup of the hostname itself.

Looking at the debug logs, it seems that the actual update API server is also connected to over IPv4. Probably an IPv6-only server would not work here either. It's currently highly unlikely to find a DDNS provider without IPv4 server, but I think Inadyn should try to connect using any OS-supported IP version available (just as curl or any modern browser does, for example).

These last two points can not be worked around so easily.

**Comment by troglobit** [comment] 2017-12-12 06:41
Hi, glad you like it! :)

This is almost a duplicate of #52, and yes we need someone to step up to help out with both development and testing of IPv6 support, which is very limited at the moment.

**Comment by acolomb** [comment] 2017-12-14 12:28
I'm currently investigating the code and will do some experiments with IPv6 lookups. It only seems to affect `tcp.c` and `cache.c` for the issues mentioned above.

Better handling of IPv6 in the configuration is another can of worms, so I'm focusing on the lookup errors for now.

**Comment by troglobit** [comment] 2017-12-14 15:14
OK, sounds reasonable.  Please make sure to verify that any changes you make don't break IPv4, preferably by testing against some provider(s). I can recommend FreeDNS.

**Comment by acolomb** [comment] 2017-12-26 17:01
So we had three problems cases here:

1. `checkip-server` with only IPv6 address--could be worked around by `checkip-cmd`.
2. `ddns-server` with an IPv6 address--not really a problem (yet) as long as IPv4 is available as a fallback and can be routed over the local network.
3. Cache preseeding by doing a DNS query for the host name, where the record to be updated is only of type AAAA.

PR #191 handles the first two cases rather easily. The last one is done in `cache.c` and needs some more careful planning. A user might want to update IPv4, IPv6, or both types of addresses with a query to the DDNS server. Therefore, the cache must also be able to hold both types simultaneously. That quickly becomes an architectural issue because we would also need two checkip connections per service, keep track of two addresses, etc. At least though, a service record should store whether it is updating a v4 or v6 address and do the initial DNS-preseeding lookup accordingly.

Maybe best we start a new issue to hash out the needed configuration and architectural changes for true multiversion IP support in Inadyn 3.0 :-)

**Closed** 2017-12-27 12:43 UTC
Labels: help-wanted

**Comment by troglobit** [comment] 2017-12-27 12:46
Agreed on the last point, either a major architectural overhaul or run two instances?  Either way, a separate issue for that would be preferable ;-)

Again, awesome work on this! :+1:

**Comment by nihilus** [comment] 2019-04-26 20:56
Any news on IPv6-support? The inadyn-mt fork has had it for some time, alas it lacks SSL/TLS support, seems like one cannot have both at the moment. I am looking into howto merge the openDNS curl_client.c to inadyn-mt.

**Comment by troglobit** [comment] 2019-04-27 07:16
There's pull request #224 with a prototype in which the conversation sort of died out. Let's continue the discussion there @nihilus since this issue is closed.
