### ISSUE TITLE
Problems with URL encoding

### ISSUE THREAD

**Issue by BrainInSight** [troglobit/inadyn#181] opened 2017-10-08 16:26 UTC
Hello,

i have problems with the URL encoding and my DynDNS provider. When I manually enter the URL https://www.direkt-domains.de/nic/update?hostname=.... everything works well (e.g. reply from server "nochg 93.243.174.230") .
However when I replace the "/" (e.g. between "nic" and "update") by "%2f" the update of the DNS entry doesn't work.

Unfortunately it seems that inadyn is generating the GET request with this these kind of URL encoding. With the following configuration

custom test {
        username = 
        password = 
        ddns-server = www.direkt-domains.de
        ddns-path = "/nic/update?hostname=test.mydomain.de&myip="
        append-myip = true
        hostname = test
}

the log outputs looks like the following

inadyn[14570]: Checking IPv4 address 93.243.174.230 ...
inadyn[14570]: IPv4 address 93.243.174.230 is valid.
inadyn[14570]: Current IP# 93.243.174.230 at custom
inadyn[14570]: Update forced for alias test, new IP# 93.243.174.230
inadyn[14570]: Sending IP# update to DDNS server, connecting to www.direkt-domains.de(185.48.116.210:443)
inadyn[14570]: Sending IP# update to DDNS server, initiating HTTPS ...
inadyn[14570]: SSL connection using ECDHE-RSA-AES256-GCM-SHA384
inadyn[14570]: Certificate OK
inadyn[14570]: SSL server cert subject: /CN=www.direkt-domains.de
inadyn[14570]: SSL server cert issuer: /C=US/O=GeoTrust Inc./OU=Domain Validated SSL/CN=GeoTrust DV SSL SHA256 CA
inadyn[14570]: Sending alias table update to DDNS server: GET %2fnic%2fupdate%3fhostname%3d%test.mydomain.de%26myip%3d93.243.174.230 HTTP/1.0
Host: www.direkt-domains.de

as you can see in the GET request the special characters "/","?","=" are replaced.

Since the generated URL is not valid the server response is

inadyn[14570]: DDNS server response: HTTP/1.1 404 Not Found
Date: Sun, 08 Oct 2017 16:14:05 GMT
Server: Apache/2.4.18 (Ubuntu)
P3P: CP="NOI NID ADMa OUR IND UNI COM NAV"
Cache-Control: private, must-revalidate
Set-Cookie: SN5231d98148f7c=pb9u7jir9762edjskp46b43uo0; path=/
Set-Cookie: SN5231d98148f7c=pb9u7jir9762edjskp46b43uo0; path=/
Vary: Host
Connection: close

Any idea how to solve this issue ?

Kind regards

**Comment by troglobit** [comment] 2017-10-08 18:02
What version of Inadyn are you using?  There were a few URL encoding issues fixed in the v2.2 release.

**Comment by BrainInSight** [comment] 2017-10-08 19:31
2.2-rc1

**Comment by troglobit** [comment] 2017-10-09 05:51
I see, then you do not have the fix for issue #152.  You should notify your distribution that this bug affects you and that it is fixed upstream (here).

**Comment by troglobit** [comment] 2017-10-09 16:03
Closing, duplicate of #152.

**Closed by troglobit** 2017-10-09 16:03 UTC
